config/routes.rb
Rails.application.routes.draw do

  #トップページ
  root to: "tasks#index"

  #ログイン・ログアウト
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  #task　
  resources :tasks
  
  #ユーザー登録
  get "signup" ,to: "users#new"  
  resources :users, only: [:new, :create]
  
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    validates :content, presence: true , length: { maximum: 255 }
    validates :status, presence: true , length: { maximum: 10 }
    
    #　1対多　user << task
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }  
  has_secure_password
  
  has_many :tasks
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper  
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    
    if login(email, password)
      flash[:success] = "ログインに成功しました。"
      redirect_to root_url
    else
      flash.now[:danger] = "ログインに失敗しました。"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました。"
    redirect_to login_url
  end
  
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user,only: [:show, :edit, :update, :destroy]
  #before_action :set_task, only: [:show, :edit, :update, :destroy]

  
  def index
    #@tasks = Task.all
    #ログイン確認後、自分専用のタスクへ移行
    if logged_in?
      @task = current_user.tasks.build
      @tasks = current_user.tasks.order(id: :desc).page(params[:page])
    end
  end

  def show
  end

  def new
    @task = Task.new#(task_params)
  end

  def create
    @task = current_user.tasks.build(task_params)
    
    if @task.save
      flash[:success] = "タスク作成完了しました。"
      redirect_to root_url
    else
      flash.now[:danger] = "タスクが作成できませんでした。"
      render :new
    end
  end

  def edit
  end

  def update
    
    if @task.update(task_params)
      flash[:success] = "タスクを更新しました。"
      redirect_to @task
    else
      flash.now[:danger] = "タスクは更新できませんでした。"
      render :edit
    end
  end

  def destroy
    @task.destroy
    
    flash[:success] = "タスクを削除しました。"
    redirect_back(fallback_location: root_url)
  end
  
  private
  
  #def set_task
    #@task = Task.find(params[:id])
  #end
  
  def task_params
    params.require(:task).permit(:content, :status)
  end
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #def index
    #@users　= User.order(id: :desc).page(params[:page]).per(25)
  #end

  #def show
    #@user = User.find(params[:id])
  #end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] ="ユーザー登録しました"
      
      redirect_to login_url
      
    else
      flash.now[:danger] = "ユーザー登録に失敗しました。"
      
      render "new"
    end
  end
  
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <ul>
    <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    
  </ul>
<% end %>

app/views/layouts/_flash_tasks.html.erb
<% flash.each do |task_type, task| %>
  <div><%= task %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KadaiTasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render "layouts/flash_tasks" %>
      
      
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.label :status, "ステータス" %>
  <%= f.text_field :status %>
  
  <%= f.label :content, 'タスク内容' %>
  <%= f.text_field :content %>

  <%= f.submit 'タスク作成' %>
<% end %>

app/views/tasks/_tasks.html.erb
<ul>

  <% tasks.each do |task| %>
  
    <li><%= link_to task.id,task %> : <%= task.status %> &gt; <%= task.content %></li>
  
  <% end %>  
    
</ul>

app/views/tasks/edit.html.erb
<h1>id: <%= @task.id %> の編集</h1>

<%= render "form" , task: @task %>

<%= link_to "一覧に戻る",tasks_path %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<%= link_to 'ログアウト', logout_path, method: :delete %></li>

<% if logged_in? %>
  <%= render "tasks",tasks: @tasks %>

  <%= link_to "新規タスク作成", new_task_path %>
  
<% else %>
  
  <%= render "sessions/new" %>
<% end %>

app/views/tasks/new.html.erb
<h1>タスク新規作成</h1>

<%= render "form" , task: @task %>

<%= link_to "一覧に戻る", tasks_path %>

app/views/tasks/show.html.erb
<h1>id: <%= @task.id %>の詳細</h1>


<% if logged_in? %>
  <p>ステータス : <%= @task.status %></p>
  <p>タスク内容 : <%= @task.content %></p>
  <%= link_to '一覧に戻る', tasks_path %>
  <%= link_to "タスクの編集",edit_task_path(@task) %>
  <%= link_to "タスクの削除",@task, method: :delete,data: {confirm: "本当に削除しますか?"} %>

<% else %>
  
  <%= render "sessions/new" %>
<% end %>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>

<%= form_with(model: @user,local: true) do |f| %>
  <%= render "layouts/error_messages",model: f.object %>
  
  <div class="form-group">
    <%= f.label :name, "名前" %>
    <%= f.text_field :name %>    
  </div>
  
  <div class="form-group">
    <%= f.label :email, "メールアドレス" %>
    <%= f.email_field :email %>    
  </div>
  
  <div class="form-group">
    <%= f.label :password, "パスワード" %>
    <%= f.password_field :password %>    
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, "パスワード再確認" %>
    <%= f.password_field :password_confirmation %>
  </div>
  
  <%= f.submit "登録" %>
<% end %>  